on:
    pull_request:

jobs:
  versiontag:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5
      - name: Check version tag
        run: |
          curl -f https://raw.githubusercontent.com/pvarki/docker-synapse-server/main/pyproject.toml -o /tmp/main_pyproject.toml || touch /tmp/main_pyproject.toml
          grep "version = " pyproject.toml >/tmp/version.txt
          grep "version = " /tmp/main_pyproject.toml >/tmp/main_version.txt
          diff /tmp/main_version.txt /tmp/version.txt && exit 1 || exit 0
  test:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Do pre-commit checks
        run: |
          pre-commit run --all-files

  docker_builds:
    runs-on: arc-runner-set
    needs: test
    steps:
      - uses: actions/checkout@v5
      - name: Build Synapse
        run: |
          docker build --target run -t synapse:run .
